### ISSUE TITLE
Error loading

### ISSUE THREAD

**Issue by Kennochas** [sanghviharshit/ha-mila#14]
Getting this error on my Mila stuff in Home assistant. Seemed to happen after updating to 8ed6332

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 353, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/mila/__init__.py", line 19, in async_setup_entry
    coordinator = MilaUpdateCoordinator(hass, entry)
  File "/config/custom_components/mila/update_coordinator.py", line 37, in __init__
    self._api = MilaApi(MilaConfigEntryAuth(hass, config_entry, MilaOauthImplementation(hass, config_entry)))
  File "/config/custom_components/mila/auth.py", line 43, in __init__
    self._auth = milasdk.MilaOauth2(token=cast(dict, config_entry.data["token"]))
KeyError: 'token'

**Comment by sanghviharshit** [comment]
This PR introduced significant changes and it requires removing the existing integration, restarting HA, and adding Mila integration again. Let me know if it doesn't work

**Comment by Coltonc188** [comment]
Hello, 

I'm trying to add this, and I have it added in HACS, and restarted my HA.  Once I have done that and go back to integration to add Mila.  I search it, and its not finding it?  I'm not sure what to do at this point.  I went back into HACS, and it no longer says pending restart, so I would think it would be there, but searching Mila, or HA-Mila nothing pulls up.

Any thoughts?

**Comment by scyto** [comment]
> This PR introduced significant changes and it requires removing the existing integration, restarting HA, and adding Mila integration again. Let me know if it doesn't work

this fixed it for me (i had been meaning to fix for months, lol) thanks for the nice integration
