### ISSUE TITLE
distance_sensor broken with 2023.11 HA release

### ISSUE THREAD

**Issue by devinsba** [sanghviharshit/ha-mila#33]
The release notes show this deprecated module was removed: https://github.com/home-assistant/core/pull/101199

```
Unexpected error fetching mila data: No module named 'homeassistant.util.distance'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 290, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mila/update_coordinator.py", line 105, in _async_update_data
    await self._build_devices(data)
  File "/config/custom_components/mila/update_coordinator.py", line 119, in _build_devices
    self.devices[id] = MilaAppliance(self, self._api, id)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mila/devices/appliance.py", line 33, in __init__
    super().__init__(coordinator, api, device_id)
  File "/config/custom_components/mila/devices/device.py", line 24, in __init__
    self._build_entities_list()
  File "/config/custom_components/mila/devices/device.py", line 92, in _build_entities_list
    from ..entities import MilaEntity
  File "/config/custom_components/mila/entities/__init__.py", line 3, in <module>
    from .location import *
  File "/config/custom_components/mila/entities/location/__init__.py", line 3, in <module>
    from .distance_sensor import MilaLocationDistanceSensor
  File "/config/custom_components/mila/entities/location/distance_sensor.py", line 9, in <module>
    from homeassistant.util.distance import convert as distance_convert
ModuleNotFoundError: No module named 'homeassistant.util.distance'
```

**Comment by scarpedon** [comment]
I was able to fix this issue by changing the code in /config/custom_components/mila/entities/location/distance_sensor.py to the following:

```
from geopy.distance import geodesic
from typing import Optional

from homeassistant.const import UnitOfLength
from homeassistant.util.unit_system import METRIC_SYSTEM
from homeassistant.util.unit_conversion import DistanceConverter
from ...const import DOMAIN
from ...devices import MilaLocation
from .sensor import MilaLocationSensor

class MilaLocationDistanceSensor(MilaLocationSensor):
    def __init__(
        self,
        device: MilaLocation
    ):
        super().__init__(device, "Station Distance", "mdi:map-marker-distance")

    @property
    def unique_id(self) -> str:
        return f"{DOMAIN}_{self.device.id}_distance".lower()

    @property
    def native_value(self):
        location_point = (float(self.device.get_value("address.point.lat")),
            float(self.device.get_value("address.point.lon")))
        station_point = (float(self.device.get_value("outdoorStation.point.lat")),
            float(self.device.get_value("outdoorStation.point.lon")))

        val = geodesic(location_point, station_point).km
        if self._is_metric:
            val = DistanceConverter.convert(val, UnitOfLength.KILOMETERS, UnitOfLength.MILES)

        return round(val,2)

    @property
    def native_unit_of_measurement(self) -> Optional[str]:
        return UnitOfLength.KILOMETERS if self._is_metric else UnitOfLength.MILES

    @property
    def _is_metric(self) -> bool:
        return self.device.hass.config.units is METRIC_SYSTEM
```

**Comment by christensenjames** [comment]
I had the same issue after updating to 2023.11. Can confirm @scarpedon's solution fixed the issue for me!

**Comment by sanghviharshit** [comment]
There is a PR waiting to be tested that fixes the issue as well. https://github.com/sanghviharshit/ha-mila/pull/32
