### ISSUE TITLE
Detected blocking call to open inside the event loop by custom integration 'mila' at custom_components/mila/update_coordinator.py, 

### ISSUE THREAD

**Issue by asucrews** [sanghviharshit/ha-mila#38]
Hello, 

I am currently on 2024.6.0b7 release and there like they added blocking call detection in 2024.6.0. not sure how to reolve this but reporting so it not a surprise. 

`Detected blocking call to open inside the event loop by custom integration 'mila' at custom_components/mila/update_coordinator.py, line 37: self._api = MilaApi(MilaConfigEntryAuth(hass, config_entry, MilaOauthImplementation(hass, config_entry))) (offender: /usr/local/lib/python3.12/site-packages/milasdk/api.py, line 38: with open(Path(__file__).parent / './gql/mila_schema.gql') as f:), please create a bug report at https://github.com/sanghviharshit/ha-mila/issues Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 188, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/setup.py", line 165, in async_setup_component result = await _async_setup_component(hass, domain, config) File "/usr/src/homeassistant/homeassistant/setup.py", line 447, in _async_setup_component await asyncio.gather( File "/usr/src/homeassistant/homeassistant/setup.py", line 449, in <genexpr> create_eager_task( File "/usr/src/homeassistant/homeassistant/util/async_.py", line 37, in create_eager_task return Task(coro, loop=loop, name=name, eager_start=True) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 742, in async_setup_locked await self.async_setup(hass, integration=integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup result = await component.async_setup_entry(hass, self) File "/config/custom_components/mila/__init__.py", line 19, in async_setup_entry coordinator = MilaUpdateCoordinator(hass, entry) File "/config/custom_components/mila/update_coordinator.py", line 37, in __init__ self._api = MilaApi(MilaConfigEntryAuth(hass, config_entry, MilaOauthImplementation(hass, config_entry)))`

**Comment by disruptivepatternmaterial** [comment]
this is not in this project, you need to open this in the lib under this project look up milasdk

**Comment by simbaja** [comment]
I haven't had much time to look into this, but it would involve refactoring the sdk a bit - this call is to get the GraphQL schema from a file.  It shouldn't pose much of an issue (small file) for the time being, but is something that should be fixed.

**Comment by simbaja** [comment]
I've made changes to fix this issue in #51 (amongst others).  All my Milas are dead, so I can't test very well, but no longer see the error in my logs.
